import defautImg from "/imageProduitDefaut.png";

export type typeProduit = {
  idCategorie: number;
  nomProduit: string;
  descriptionProduit: string;
  imageProduit: string;
  prixProduit: string;
};

export const listeProduits: typeProduit[] = [
  // Sauces Maison
  {
    idCategorie: 1,
    nomProduit: "Bolognaise",
    descriptionProduit: "350gr",
    imageProduit: defautImg,
    prixProduit: "20 dt",
  },
  {
    idCategorie: 1,
    nomProduit: "Fruits de mer",
    descriptionProduit: "350gr",
    imageProduit: defautImg,
    prixProduit: "30 dt",
  },
  {
    idCategorie: 1,
    nomProduit: "Thon Basilic",
    descriptionProduit: "350gr",
    imageProduit: defautImg,
    prixProduit: "25 dt",
  },
  {
    idCategorie: 1,
    nomProduit: "Ail Basilic",
    descriptionProduit: "350gr",
    imageProduit: defautImg,
    prixProduit: "15 dt",
  },
  {
    idCategorie: 1,
    nomProduit: "Putanesca",
    descriptionProduit: "350gr",
    imageProduit: defautImg,
    prixProduit: "25 dt",
  },
  {
    idCategorie: 1,
    nomProduit: "Sauce à l'ail",
    descriptionProduit: "220gr",
    imageProduit: defautImg,
    prixProduit: "10 dt",
  },
  {
    idCategorie: 1,
    nomProduit: "Samouraï",
    descriptionProduit: "220gr",
    imageProduit: defautImg,
    prixProduit: "10 dt",
  },
  {
    idCategorie: 1,
    nomProduit: "Barbecue",
    descriptionProduit: "220gr",
    imageProduit: defautImg,
    prixProduit: "10 dt",
  },

  // Produits Mer
  {
    idCategorie: 2,
    nomProduit: "Boutargue entière tunisienne",
    descriptionProduit: "Sous cire et sous vide",
    imageProduit: defautImg,
    prixProduit: "350 dt/kg",
  },
  {
    idCategorie: 2,
    nomProduit: "Boutargue râpée",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "350 dt/kg",
  },
  {
    idCategorie: 2,
    nomProduit: "Huîtres de saison vivantes",
    descriptionProduit: "12 huitres",
    imageProduit: defautImg,
    prixProduit: "30 dt",
  },
  {
    idCategorie: 2,
    nomProduit: "Noix de Saint Jacques",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "300 dt/kg",
  },
  {
    idCategorie: 2,
    nomProduit: "Œufs de seiches à la Valencienne",
    descriptionProduit: "Bocal 350gr",
    imageProduit: defautImg,
    prixProduit: "80 dt",
  },
  {
    idCategorie: 2,
    nomProduit: "Saumon cru en darnes",
    descriptionProduit: "Sous vide",
    imageProduit: defautImg,
    prixProduit: "120 dt/kg",
  },
  {
    idCategorie: 2,
    nomProduit: "Saumon fumé",
    descriptionProduit: "Sous vide, 100gr",
    imageProduit: defautImg,
    prixProduit: "20 dt",
  },
  {
    idCategorie: 2,
    nomProduit: "Espadon en tranches",
    descriptionProduit: "Sous vide",
    imageProduit: defautImg,
    prixProduit: "60 dt/kg",
  },
  {
    idCategorie: 2,
    nomProduit: "Calamars congelés frais",
    descriptionProduit: "Sous vide",
    imageProduit: defautImg,
    prixProduit: "80 dt/kg",
  },
  {
    idCategorie: 2,
    nomProduit: "Langoustes congelées",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "120 dt/kg",
  },
  {
    idCategorie: 2,
    nomProduit: "Cigales congelées",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "120 dt/kg",
  },
  {
    idCategorie: 2,
    nomProduit: "Crevettes Royales",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "Prix selon la saison",
  },
  {
    idCategorie: 2,
    nomProduit: "Crevette Rouge de Mazzara",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "200 dt/kg",
  },
  {
    idCategorie: 2,
    nomProduit: "Langoustines",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "180 dt/kg",
  },
  {
    idCategorie: 2,
    nomProduit: "Poulpe gros calibre",
    descriptionProduit: "Vidé et battu",
    imageProduit: defautImg,
    prixProduit: "80 dt/kg",
  },
  {
    idCategorie: 2,
    nomProduit: "Filets de Thon Rouge à l’huile",
    descriptionProduit: "Bocal 1kg",
    imageProduit: defautImg,
    prixProduit: "100 dt",
  },
  {
    idCategorie: 2,
    nomProduit: "Ventrèche de Thon Rouge à l’huile",
    descriptionProduit: "Bocal 1kg",
    imageProduit: defautImg,
    prixProduit: "120 dt",
  },
  {
    idCategorie: 2,
    nomProduit: "Filets de Sardine marinés à l’ancienne",
    descriptionProduit: "Bocal 220gr",
    imageProduit: defautImg,
    prixProduit: "20 dt",
  },
  {
    idCategorie: 2,
    nomProduit: "Chevrettes marinées",
    descriptionProduit: "Bocal 350gr",
    imageProduit: defautImg,
    prixProduit: "50 dt",
  },
  {
    idCategorie: 2,
    nomProduit: "Salade de Poulpe",
    descriptionProduit: "440gr",
    imageProduit: defautImg,
    prixProduit: "60 dt",
  },
  {
    idCategorie: 2,
    nomProduit: "Carpaccio de Poulpe",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "20 dt/pers",
  },
  {
    idCategorie: 2,
    nomProduit: "Seiches sautées à l’ail",
    descriptionProduit: "Bocal 350gr",
    imageProduit: defautImg,
    prixProduit: "80 dt",
  },

  // Plateaux
  {
    idCategorie: 3,
    nomProduit: "Plateau Fromage",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "",
  },
  {
    idCategorie: 3,
    nomProduit: "Plateau Charcuterie",
    descriptionProduit: "Porc ou Halal",
    imageProduit: defautImg,
    prixProduit: "",
  },
  {
    idCategorie: 3,
    nomProduit: "Plateau mixte charcuterie & fromages",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "",
  },
  {
    idCategorie: 3,
    nomProduit: "Plateau Raclette",
    descriptionProduit: "Fromage et charcuteries pour les raclettes",
    imageProduit: defautImg,
    prixProduit: "",
  },
  {
    idCategorie: 3,
    nomProduit: "Plateau fruits de mer",
    descriptionProduit: "Selon la saison",
    imageProduit: defautImg,
    prixProduit: "",
  },

  // Plats Cuisinés
  {
    idCategorie: 4,
    nomProduit: "Marcassin effiloché confit sauce rouge",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "",
  },
  {
    idCategorie: 4,
    nomProduit: "Marcassin confit vin blanc",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "",
  },
  {
    idCategorie: 4,
    nomProduit: "Jarret de porc confit",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "",
  },
  {
    idCategorie: 4,
    nomProduit: "Cuissot de Marcassin au four",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "",
  },
  {
    idCategorie: 4,
    nomProduit: "Cassoulet Castelnaudary",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "",
  },
  {
    idCategorie: 4,
    nomProduit: "Bœuf Bourguignon",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "",
  },
  {
    idCategorie: 4,
    nomProduit: "Choucroute alsacienne garnie",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "",
  },
  {
    idCategorie: 4,
    nomProduit: "Dinde farcie",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "",
  },
  {
    idCategorie: 4,
    nomProduit: "Canette au four façon Créole",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "",
  },
  {
    idCategorie: 4,
    nomProduit: "Mloukhya tunisienne",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "",
  },
  {
    idCategorie: 4,
    nomProduit: "Kammounia de Poulpe",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "",
  },
  {
    idCategorie: 4,
    nomProduit: "Couscous",
    descriptionProduit: "Agneau, poulet, poulpe ou mérou",
    imageProduit: defautImg,
    prixProduit: "",
  },
  {
    idCategorie: 4,
    nomProduit: "Calamars farcis",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "",
  },
  {
    idCategorie: 4,
    nomProduit: "Paella à la Valencienne",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "",
  },
  {
    idCategorie: 4,
    nomProduit: "Lasagnes maison",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "",
  },
  {
    idCategorie: 4,
    nomProduit: "Parmigiana",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "",
  },
  {
    idCategorie: 4,
    nomProduit: "Gratin Dauphinois",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "",
  },
  {
    idCategorie: 4,
    nomProduit: "Quiches",
    descriptionProduit: "Plusieurs variétés",
    imageProduit: defautImg,
    prixProduit: "",
  },
  {
    idCategorie: 4,
    nomProduit: "Escargots en sauce vin rouge",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "",
  },
  {
    idCategorie: 4,
    nomProduit: "Langoustes et Cigales en sauce",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "",
  },

  // Soupes
  {
    idCategorie: 5,
    nomProduit: "Soupe quatre légumes",
    descriptionProduit: "Bouteille 1L",
    imageProduit: defautImg,
    prixProduit: "",
  },
  {
    idCategorie: 5,
    nomProduit: "Bouillabaisse",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "",
  },
  {
    idCategorie: 5,
    nomProduit: "Rascasse",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "",
  },
  {
    idCategorie: 5,
    nomProduit: "Poissons de roche à la tunisienne",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "",
  },
  {
    idCategorie: 5,
    nomProduit: "Filet de lotte",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "",
  },
  {
    idCategorie: 5,
    nomProduit: "Tchich Karnit",
    descriptionProduit: "Soupe au poulpe",
    imageProduit: defautImg,
    prixProduit: "",
  },
  {
    idCategorie: 5,
    nomProduit: "Soupe potiron",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "",
  },
  {
    idCategorie: 5,
    nomProduit: "Soupe saumon",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "",
  },
  {
    idCategorie: 5,
    nomProduit: "Bisque langouste",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "",
  },

  // Rillettes
  {
    idCategorie: 6,
    nomProduit: "Rillettes de Porc",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "20 dt",
  },
  {
    idCategorie: 6,
    nomProduit: "Rillettes de Sanglier",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "20 dt",
  },
  {
    idCategorie: 6,
    nomProduit: "Rillettes de Marcassin",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "20 dt",
  },
  {
    idCategorie: 6,
    nomProduit: "Rillettes de Canard",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "25 dt",
  },
  {
    idCategorie: 6,
    nomProduit: "Rillettes de Lapin",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "25 dt",
  },
  {
    idCategorie: 6,
    nomProduit: "Rillettes aux deux Saumons",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "30 dt",
  },
  {
    idCategorie: 6,
    nomProduit: "Rillettes au Crabe",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "30 dt",
  },
  {
    idCategorie: 6,
    nomProduit: "Rillettes au Thon",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "25 dt",
  },
  {
    idCategorie: 6,
    nomProduit: "Rillettes Sardine Paprika",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "20 dt",
  },
  // Tartinothèque
  {
    idCategorie: 7,
    nomProduit: "Tapenade Noire de Marseille",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "10 dt",
  },
  {
    idCategorie: 7,
    nomProduit: "Tapenade Verte",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "10 dt",
  },
  {
    idCategorie: 7,
    nomProduit: "Tapenade Maltaise",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "10 dt",
  },
  {
    idCategorie: 7,
    nomProduit: "Tapenade Mexicaine",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "10 dt",
  },
  {
    idCategorie: 7,
    nomProduit: "Houmous Nature",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "15 dt",
  },
  {
    idCategorie: 7,
    nomProduit: "Crème de Citron",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "10 dt",
  },
  {
    idCategorie: 7,
    nomProduit: "Caviar de Carottes",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "10 dt",
  },
  {
    idCategorie: 7,
    nomProduit: "Caviar d’Aubergine",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "15 dt",
  },
  {
    idCategorie: 7,
    nomProduit: "Caviar d’Artichauts",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "15 dt",
  },
  {
    idCategorie: 7,
    nomProduit: "Confit de Piment Rouge",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "20 dt",
  },
  {
    idCategorie: 7,
    nomProduit: "Chutney oignons",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "20 dt",
  },

  // Kif-Apéro
  {
    idCategorie: 8,
    nomProduit: "Tomates séchées à la Provençale",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "10 dt",
  },
  {
    idCategorie: 8,
    nomProduit: "Œufs de cailles marinés",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "25 dt",
  },
  {
    idCategorie: 8,
    nomProduit: "Escargots à la Bourguignonne",
    descriptionProduit: "12 pièces",
    imageProduit: defautImg,
    prixProduit: "25 dt",
  },
  {
    idCategorie: 8,
    nomProduit: "Bnedeks boulettes de viande à la menthe",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "40 dt",
  },
  {
    idCategorie: 8,
    nomProduit: "Kaddid de merguez séchées dans l’huile",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "60 dt",
  },
  {
    idCategorie: 8,
    nomProduit: "Anchois de Kelibia marinés",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "30 dt",
  },
  {
    idCategorie: 8,
    nomProduit: "Olives marinées à la Sicilienne",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "15 dt",
  },
  {
    idCategorie: 8,
    nomProduit: "Gambos d’artichauts",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "25 dt",
  },
  {
    idCategorie: 8,
    nomProduit: "Cœurs d’Artichauts marinés",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "15 dt",
  },
  {
    idCategorie: 8,
    nomProduit: "Cornichons à la Provençale",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "10 dt",
  },
  {
    idCategorie: 8,
    nomProduit: "Câpres de Ghar Melh",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "10 dt",
  },
  {
    idCategorie: 8,
    nomProduit: "Salade Mechouia douce grand",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "15 dt",
  },
  {
    idCategorie: 8,
    nomProduit: "Salade Mechouia piquante grand",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "15 dt",
  },
  {
    idCategorie: 8,
    nomProduit: "Salade Mechouia douce petit",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "10 dt",
  },
  {
    idCategorie: 8,
    nomProduit: "Salade Mechouia piquante petit",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "10 dt",
  },
  {
    idCategorie: 8,
    nomProduit: "Pili Pili de Sicile",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "15 dt",
  },
  {
    idCategorie: 8,
    nomProduit: "Piments de Cayenne",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "10 dt",
  },
  {
    idCategorie: 8,
    nomProduit: "Harissa Berbère",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "10 dt",
  },
  {
    idCategorie: 8,
    nomProduit: "Harissa Fumée",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "10 dt",
  },
  {
    idCategorie: 8,
    nomProduit: "Sel de Guérande",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "20 dt",
  },
  {
    idCategorie: 8,
    nomProduit: "Sel de l’Himalaya",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "20 dt",
  },
  {
    idCategorie: 8,
    nomProduit: "Peperoncino Italiano",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "15 dt",
  },
  {
    idCategorie: 8,
    nomProduit: "Ail Confit dans sa chemise",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "10 dt",
  },
  {
    idCategorie: 8,
    nomProduit: "Pâte de Truffe noire",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "80 dt",
  },
  {
    idCategorie: 8,
    nomProduit: "Porcini séchés",
    descriptionProduit: "Champignons sauvages",
    imageProduit: defautImg,
    prixProduit: "40 dt",
  },

  // Produits Terre Volaille
  {
    idCategorie: 9,
    nomProduit: "Foie Gras Nature",
    descriptionProduit: "Terrine 220gr",
    imageProduit: defautImg,
    prixProduit: "200 dt",
  },
  {
    idCategorie: 9,
    nomProduit: "Foie Gras Sel de Guérande",
    descriptionProduit: "Terrine 220gr",
    imageProduit: defautImg,
    prixProduit: "210 dt",
  },
  {
    idCategorie: 9,
    nomProduit: "Foie Gras Truffe noire",
    descriptionProduit: "Terrine 220gr",
    imageProduit: defautImg,
    prixProduit: "240 dt",
  },
  {
    idCategorie: 9,
    nomProduit: "Foie Gras Cru en lobes entiers",
    descriptionProduit: "Environ 400gr",
    imageProduit: defautImg,
    prixProduit: "500 dt/kg",
  },
  {
    idCategorie: 9,
    nomProduit: "Magret de canard cru",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "200 dt/kg",
  },
  {
    idCategorie: 9,
    nomProduit: "Cuisses de canard crues",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "180 dt/kg",
  },
  {
    idCategorie: 9,
    nomProduit: "Gésiers de Canard",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "50 dt/kg",
  },
  {
    idCategorie: 9,
    nomProduit: "Graisse de Canard",
    descriptionProduit: "1 litre",
    imageProduit: defautImg,
    prixProduit: "100 dt",
  },
  {
    idCategorie: 9,
    nomProduit: "Canard entier cru du Gers",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "40 dt/kg",
  },

  // Produits Terre Porc
  {
    idCategorie: 10,
    nomProduit: "Côtes dans l’échine",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "70 dt",
  },
  {
    idCategorie: 10,
    nomProduit: "Rôtis de porc",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "70 dt",
  },
  {
    idCategorie: 10,
    nomProduit: "Filet mignon",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "110 dt",
  },
  {
    idCategorie: 10,
    nomProduit: "Jarret de porc",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "80 dt",
  },
  {
    idCategorie: 10,
    nomProduit: "Travers / Ribs",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "70 dt",
  },
  {
    idCategorie: 10,
    nomProduit: "Couenne langue pieds oreilles",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "60 dt",
  },
  {
    idCategorie: 10,
    nomProduit: "Saindoux",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "70 dt",
  },
  {
    idCategorie: 10,
    nomProduit: "Chair à saucisse",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "70 dt",
  },
  {
    idCategorie: 10,
    nomProduit: "Jambon blanc",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "120 dt",
  },
  {
    idCategorie: 10,
    nomProduit: "Saucisse de Toulouse",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "70 dt",
  },
  {
    idCategorie: 10,
    nomProduit: "Saucisse de Francfort fumée",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "70 dt",
  },
  {
    idCategorie: 10,
    nomProduit: "Saucisses blanches Weisswurst",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "70 dt",
  },
  {
    idCategorie: 10,
    nomProduit: "Pâté de campagne en tranche",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "120 dt",
  },
  {
    idCategorie: 10,
    nomProduit: "Fromage de tête",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "80 dt",
  },
  {
    idCategorie: 10,
    nomProduit: "Filets de porc",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "90 dt",
  },
  {
    idCategorie: 10,
    nomProduit: "Cuissot ou épaule de marcassin",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "60 dt",
  },
  {
    idCategorie: 10,
    nomProduit: "Longe de marcassin",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "100 dt",
  },
  {
    idCategorie: 10,
    nomProduit: "Poitrine de porc crue",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "80 dt",
  },
  {
    idCategorie: 10,
    nomProduit: "Poitrine de porc fumée",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "90 dt",
  },
  {
    idCategorie: 10,
    nomProduit: "Guanciale pour Carbonara",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "150 dt",
  },
  {
    idCategorie: 10,
    nomProduit: "Pancetta",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "120 dt",
  },
  {
    idCategorie: 10,
    nomProduit: "Lardons fumés",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "100 dt",
  },
  {
    idCategorie: 10,
    nomProduit: "Chorizo",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "120 dt",
  },
  {
    idCategorie: 10,
    nomProduit: "Saucisse sèche",
    descriptionProduit: "220gr",
    imageProduit: defautImg,
    prixProduit: "40 dt",
  },
  {
    idCategorie: 10,
    nomProduit: "Rosette de Lyon",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "180 dt",
  },
  {
    idCategorie: 10,
    nomProduit: "Saucisson au poivre",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "180 dt",
  },
  {
    idCategorie: 10,
    nomProduit: "Saucisson aux herbes",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "180 dt",
  },
  {
    idCategorie: 10,
    nomProduit: "Jambon de Parme",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "200 dt",
  },
  {
    idCategorie: 10,
    nomProduit: "Jambon de Paris",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "150 dt",
  },
  {
    idCategorie: 10,
    nomProduit: "Mortadelle",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "120 dt",
  },
  {
    idCategorie: 10,
    nomProduit: "Bacon fumé prédécoupé sous vide",
    descriptionProduit: "",
    imageProduit: defautImg,
    prixProduit: "120 dt",
  },
  {
    idCategorie: 10,
    nomProduit: "Pesto",
    descriptionProduit: "Bocal 220gr",
    imageProduit: defautImg,
    prixProduit: "30 dt",
  },
];
